# Site settings
title: TSA
#description: Katsutoshi Seki's personal note.
# author: <a href="http://wwws.amazon.co.jp/-/e/B00ADGVC1W">関 勝寿</a>
#author: <a href="https://tattsuast.github.io/toyo/">たっつー＊</a>
#author-en: <a href="https://scholar.google.com/citations?user=Gs_ABawAAAAJ">Katsutoshi Seki</a>
baseurl: "" 
url: "https://tattsuast.github.io" 
repository: "https://github.com/tattsuast/tattsuast.github.io"
#popular: "/2022/12/27/popular2022/"

# Versions of JavaScript
# Last update on 2023-09-17
jquery-version: "3.7.0" # jQuery https://jquery.com/download/

# Build settings
markdown: kramdown
permalink: pretty

plugins:
  - jekyll-coffeescript
  - jekyll-gist
  - jekyll-paginate
  - jekyll-feed
whitelist:
  - jekyll-coffeescript
  - jekyll-gist
  - jekyll-paginate
  - jekyll-feed

# pagination
paginate: 10
pagenate_path: "page:num"

# highlighter: "rouge"

exclude: [vendor]